name: kcounter
description: A Flutter app that allows to count things that matter to you.

publish_to: 'none'

version: 1.2.0+10

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: 1.21.0
  firebase_analytics: 9.3.2
  firebase_crashlytics: 2.8.8
  firebase_database: 9.1.2

  logger: 1.1.0
  localstore: 1.2.3

  equatable: 2.0.5
  collection: 1.16.0
  # group counter logs dependencies start
  week_of_year: 2.0.0
  intl: 0.17.0
  # group counter logs dependencies end

  # UI dependencies
  flutter_neumorphic: 3.2.0
  flutter_riverpod: 1.0.4
  flutter_colorpicker: 1.0.3
  flutter_svg: 1.1.4
  firebase_auth: 3.6.4
  google_sign_in: 5.4.1
  shake: 2.1.0
  flutter_local_notifications: 9.8.0+1
  timezone: 0.8.0
  rxdart: 0.27.5
  syncfusion_flutter_charts: 20.2.44

dev_dependencies:
  flutter_test:
    sdk: flutter

  mocktail: 0.3.0
  mek_lints: 0.3.0
  flutter_launcher_icons: "^0.9.2"
  dart_code_metrics: 4.17.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true


flutter:
  uses-material-design: true

  assets:
    - assets/images/
