name: kcounter
description: A Flutter app that allows to count things that matter to you.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.12.0
  firebase_analytics: ^9.1.0
  firebase_crashlytics: ^2.5.0
  firebase_database: ^9.0.6

  logger: ^1.1.0
  localstore: ^1.2.1

  equatable: ^2.0.3
  collection: ^1.15.0
  # group counter logs deps start
  week_of_year: ^2.0.0
  intl: ^0.17.0
  # group counter logs deps end

  # UI deps
  flutter_neumorphic: ^3.2.0
  flutter_riverpod: ^1.0.3
  flutter_colorpicker: ^1.0.3
  charts_flutter: ^0.12.0
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  mocktail: 0.2.0
  mek_lints: ^0.1.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
