// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvgcUZXWb9OwAo1MjKXdEf7EJWcbj2c0Y',
    appId: '1:544972692002:android:ed6facd8b03f58358e087b',
    messagingSenderId: '544972692002',
    projectId: 'stuff-counter',
    storageBucket: 'stuff-counter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCErpIQgGywodisdZZwE4oMU1Z07-yHog',
    appId: '1:544972692002:ios:3a7c6ec15d4c71308e087b',
    messagingSenderId: '544972692002',
    projectId: 'stuff-counter',
    storageBucket: 'stuff-counter.appspot.com',
    iosClientId: '544972692002-s3f8pk1te07rpbfe4eg7gmmchnkvg167.apps.googleusercontent.com',
    iosBundleId: 'net.kuama.stuffcounter',
  );
}
