// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE2cvxQSEUV3X_1yb8s0_BYDl4Kb0sXiA',
    appId: '1:544972692002:web:377f770251b5d6108e087b',
    messagingSenderId: '544972692002',
    projectId: 'stuff-counter',
    authDomain: 'stuff-counter.firebaseapp.com',
    databaseURL: 'https://stuff-counter-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'stuff-counter.appspot.com',
    measurementId: 'G-MFPHFR97B0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvgcUZXWb9OwAo1MjKXdEf7EJWcbj2c0Y',
    appId: '1:544972692002:android:e7fe203e56f7d6898e087b',
    messagingSenderId: '544972692002',
    projectId: 'stuff-counter',
    databaseURL: 'https://stuff-counter-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'stuff-counter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCErpIQgGywodisdZZwE4oMU1Z07-yHog',
    appId: '1:544972692002:ios:7b2e267bd4d2a3dd8e087b',
    messagingSenderId: '544972692002',
    projectId: 'stuff-counter',
    databaseURL: 'https://stuff-counter-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'stuff-counter.appspot.com',
    iosClientId: '544972692002-8p565hv8dt84514ren2l8r6pfd840jef.apps.googleusercontent.com',
    iosBundleId: 'com.kcounter.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCErpIQgGywodisdZZwE4oMU1Z07-yHog',
    appId: '1:544972692002:ios:7b2e267bd4d2a3dd8e087b',
    messagingSenderId: '544972692002',
    projectId: 'stuff-counter',
    databaseURL: 'https://stuff-counter-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'stuff-counter.appspot.com',
    iosClientId: '544972692002-8p565hv8dt84514ren2l8r6pfd840jef.apps.googleusercontent.com',
    iosBundleId: 'com.kcounter.app',
  );
}
