name: Build & Analize &  Test
on:
  push:
    paths: [ '**.dart' ]

jobs:
  integration:
    # The type of machine to run the job on. [windows,macos, ubuntu , self-hosted]
    runs-on: ubuntu-latest
    # Sequence of tasks called
    steps:
      # The branch or tag ref that triggered the workflow will be checked out.
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '12.x'
      # Setup a flutter environment.
      # https://github.com/marketplace/actions/flutter-action
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
          flutter-version: '2.10.x'
          cache: true
          cache-key: flutter
      - name: Resolve flutter/dart dependencies
        run: flutter pub get
      - name: Check the format of the code
        run: find . -name "*.dart" ! -name "*.g.dart" ! -name "env.dart" ! -name "r.dart" ! -name "en.dart" ! -name "firebase_options.dart" | tr '\n' ' ' | xargs flutter format -l 100 --set-exit-if-changed --help --verbose
      # Run static analysis code
      - name: Analyze the code
        run: flutter analyze --no-fatal-infos
      # Run flutter widgets tests and unit tests
      - name: Test the code
        run: flutter test